### PR TITLE
fix null versionstamp

### LINKED ISSUE #85: null versionstamp checks always failed (nodejs)
version: 0.8.1 (platform: mac)
example:

```js
import { openKv } from "@deno/kv";
import { unlink } from "node:fs/promises";

try {
  await unlink("test.db");
} catch {}
const kv = await openKv("test.db", {});
const key = ["test"];
const empty = await kv.get(key);
const result = await kv.atomic().check(empty).commit();
console.log(result);
```

always got ok: false

but the docs say:
> A check with a null versionstamp checks that the key-value pair does not currently exist in the KV store.

### PR DESCRIPTION
**Pull request by codehz**
fix #85
use undefined is fine here, the generated type is wrong (the encodeBinary function actually compare the value with undefined)

### CODE REVIEW

File: npm/src/proto_based.ts [hunk 1]
```diff
@@ -264,7 +260,9 @@ function computeKvCheckMessage(
   return {
     key: packKey(key),
     versionstamp: (versionstamp === null || versionstamp === undefined)
-      ? emptyVersionstamp
+      /* in proto3 all fields are optional, but the generated types don't
+       * like it, so we have to cast it manually */
+      ? undefined as unknown as Uint8Array
```
Comment (losfair) [inline npm/src/proto_based.ts:265]: I think you can just use `new Uint8Array()` here - the zero value is not distinguishable from an unset value in protobuf.

Comment (codehz) [reply npm/src/proto_based.ts:265]: While it will work, it will be encoded and take up some bandwidth (I actually measure it output).

**Review by losfair — APPROVED** [review]
